In [4]:
import numpy as np
B = np.arange(3)
print B
print np.exp(B)


[0 1 2]
[ 1.          2.71828183  7.3890561 ]


In [3]:
print np.sqrt(B)

[ 0.          1.          1.41421356]


In [8]:
#Return the floor of the input
a = np.floor(10*np.random.random((3,4)))
print a

print('======')
#a.shape
## flatten the array
print a.ravel()
print('======')
a.shape = (6, 2)
print a 
print('======')

print a.T
print('======')
print a.resize((2,6))
print('======')
print a

#If a dimension is given as -1 in a reshaping operation, the other dimensions are automatically calculated:
#a.reshape(3,-1)

[[ 8.  1.  2.  5.]
 [ 0.  5.  0.  2.]
 [ 0.  9.  7.  4.]]
[ 8.  1.  2.  5.  0.  5.  0.  2.  0.  9.  7.  4.]
[[ 8.  1.]
 [ 2.  5.]
 [ 0.  5.]
 [ 0.  2.]
 [ 0.  9.]
 [ 7.  4.]]
[[ 8.  2.  0.  0.  0.  7.]
 [ 1.  5.  5.  2.  9.  4.]]
None
[[ 8.  1.  2.  5.  0.  5.]
 [ 0.  2.  0.  9.  7.  4.]]


In [9]:
a = np.floor(10*np.random.random((2,2)))
b = np.floor(10*np.random.random((2,2)))
print a
print '---'
print b
print '---'
print np.hstack((a,b)) # 横向拼接
print('======')
print np.vstack((a,b)) # 纵向拼接
#np.hstack((a,b))

[[ 1.  4.]
 [ 5.  1.]]
---
[[ 0.  4.]
 [ 2.  2.]]
---
[[ 1.  4.  0.  4.]
 [ 5.  1.  2.  2.]]
[[ 1.  4.]
 [ 5.  1.]
 [ 0.  4.]
 [ 2.  2.]]


In [12]:
a = np.floor(10*np.random.random((2,12)))
print a
print np.hsplit(a,3) #横向切分
print np.hsplit(a,(3,4))   # Split a after the third and the fourth column
a = np.floor(10*np.random.random((12,2)))
print a
np.vsplit(a,3) 

[[ 2.  7.  8.  0.  0.  8.  9.  2.  4.  2.  2.  6.]
 [ 2.  4.  2.  9.  0.  5.  3.  2.  0.  6.  0.  5.]]
[array([[ 2.,  7.,  8.,  0.],
       [ 2.,  4.,  2.,  9.]]), array([[ 0.,  8.,  9.,  2.],
       [ 0.,  5.,  3.,  2.]]), array([[ 4.,  2.,  2.,  6.],
       [ 0.,  6.,  0.,  5.]])]
[array([[ 2.,  7.,  8.],
       [ 2.,  4.,  2.]]), array([[ 0.],
       [ 9.]]), array([[ 0.,  8.,  9.,  2.,  4.,  2.,  2.,  6.],
       [ 0.,  5.,  3.,  2.,  0.,  6.,  0.,  5.]])]
[[ 5.  9.]
 [ 4.  3.]
 [ 8.  0.]
 [ 4.  7.]
 [ 0.  2.]
 [ 2.  4.]
 [ 6.  1.]
 [ 7.  6.]
 [ 3.  4.]
 [ 1.  0.]
 [ 8.  6.]
 [ 5.  5.]]


[array([[ 5.,  9.],
        [ 4.,  3.],
        [ 8.,  0.],
        [ 4.,  7.]]), array([[ 0.,  2.],
        [ 2.,  4.],
        [ 6.,  1.],
        [ 7.,  6.]]), array([[ 3.,  4.],
        [ 1.,  0.],
        [ 8.,  6.],
        [ 5.,  5.]])]

In [13]:
#Simple assignments make no copy of array objects or of their data.
a = np.arange(12)
b = a
# a and b are two names for the same ndarray object
print b is a
b.shape = 3,4
print a.shape
print id(a)
print id(b)

True
(3, 4)
4478334816
4478334816


In [15]:
#The view method creates a new array object that looks at the same data.
c = a.view()
print c is a
c.shape = 2,6
print a.shape
c[0,4] = 1234 #地址不同 但是里面元素公用 所以值也跟着改变
a

False
(3, 4)


array([[   0,    1,    2,    3],
       [1234,    5,    6,    7],
       [   8,    9,   10,   11]])

In [16]:
#The copy method makes a complete copy of the array and its data.
d = a.copy() #深复制
print d is a
d[0,0] = 9999 #c
print d 
print a 

False
[[9999    1    2    3]
 [1234    5    6    7]
 [   8    9   10   11]]
[[   0    1    2    3]
 [1234    5    6    7]
 [   8    9   10   11]]
